-- Assignment and Submission Management System
-- PostgreSQL schema and sample data
-- The application also applies the EF Core migration and C# seed data automatically.

BEGIN;

CREATE TABLE IF NOT EXISTS classes (
    "Id" uuid PRIMARY KEY,
    "Name" varchar(100) NOT NULL,
    "Section" varchar(50) NOT NULL,
    "AcademicYear" varchar(20) NOT NULL,
    CONSTRAINT "UQ_classes_name_section_year" UNIQUE ("Name", "Section", "AcademicYear")
);

CREATE TABLE IF NOT EXISTS subjects (
    "Id" uuid PRIMARY KEY,
    "Name" varchar(120) NOT NULL,
    "Code" varchar(30) NOT NULL UNIQUE
);

CREATE TABLE IF NOT EXISTS users (
    "Id" uuid PRIMARY KEY,
    "FullName" varchar(120) NOT NULL,
    "Email" varchar(180) NOT NULL UNIQUE,
    "PasswordHash" varchar(500) NOT NULL,
    "Role" varchar(20) NOT NULL CHECK ("Role" IN ('Admin', 'Teacher', 'Student')),
    "ClassId" uuid NULL REFERENCES classes("Id") ON DELETE RESTRICT,
    "IsActive" boolean NOT NULL DEFAULT true,
    "CreatedAt" timestamptz NOT NULL DEFAULT NOW(),
    CONSTRAINT "CK_users_student_class" CHECK ("Role" = 'Student' OR "ClassId" IS NULL)
);

CREATE TABLE IF NOT EXISTS teaching_assignments (
    "Id" uuid PRIMARY KEY,
    "TeacherId" uuid NOT NULL REFERENCES users("Id") ON DELETE RESTRICT,
    "ClassId" uuid NOT NULL REFERENCES classes("Id") ON DELETE RESTRICT,
    "SubjectId" uuid NOT NULL REFERENCES subjects("Id") ON DELETE RESTRICT,
    "CreatedAt" timestamptz NOT NULL DEFAULT NOW(),
    CONSTRAINT "UQ_teaching_scope" UNIQUE ("TeacherId", "ClassId", "SubjectId")
);

CREATE TABLE IF NOT EXISTS assignments (
    "Id" uuid PRIMARY KEY,
    "TeacherId" uuid NOT NULL REFERENCES users("Id") ON DELETE RESTRICT,
    "ClassId" uuid NOT NULL REFERENCES classes("Id") ON DELETE RESTRICT,
    "SubjectId" uuid NOT NULL REFERENCES subjects("Id") ON DELETE RESTRICT,
    "Title" varchar(180) NOT NULL,
    "Description" varchar(5000) NOT NULL,
    "Deadline" timestamptz NOT NULL,
    "MaxMarks" numeric(8,2) NOT NULL CHECK ("MaxMarks" > 0),
    "Status" varchar(20) NOT NULL CHECK ("Status" IN ('Draft', 'Published')),
    "AllowResubmission" boolean NOT NULL DEFAULT true,
    "CreatedAt" timestamptz NOT NULL DEFAULT NOW(),
    "UpdatedAt" timestamptz NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS submissions (
    "Id" uuid PRIMARY KEY,
    "AssignmentId" uuid NOT NULL REFERENCES assignments("Id") ON DELETE CASCADE,
    "StudentId" uuid NOT NULL REFERENCES users("Id") ON DELETE RESTRICT,
    "AnswerText" varchar(10000) NOT NULL,
    "Status" varchar(20) NOT NULL CHECK ("Status" IN ('Submitted', 'Reviewed', 'Returned')),
    "Marks" numeric(8,2) NULL,
    "Feedback" varchar(3000) NULL,
    "SubmittedAt" timestamptz NOT NULL DEFAULT NOW(),
    "UpdatedAt" timestamptz NOT NULL DEFAULT NOW(),
    "ReviewedAt" timestamptz NULL,
    CONSTRAINT "UQ_submission_assignment_student" UNIQUE ("AssignmentId", "StudentId")
);

CREATE TABLE IF NOT EXISTS settings (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "Key" varchar(100) NOT NULL UNIQUE,
    "Value" varchar(1000) NOT NULL,
    "Description" varchar(500) NULL,
    "UpdatedAt" timestamptz NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS "IX_users_ClassId" ON users ("ClassId");
CREATE INDEX IF NOT EXISTS "IX_assignments_TeacherId" ON assignments ("TeacherId");
CREATE INDEX IF NOT EXISTS "IX_assignments_SubjectId" ON assignments ("SubjectId");
CREATE INDEX IF NOT EXISTS "IX_assignments_scope_status_deadline" ON assignments ("ClassId", "SubjectId", "Status", "Deadline");
CREATE INDEX IF NOT EXISTS "IX_teaching_assignments_ClassId" ON teaching_assignments ("ClassId");
CREATE INDEX IF NOT EXISTS "IX_teaching_assignments_SubjectId" ON teaching_assignments ("SubjectId");
CREATE INDEX IF NOT EXISTS "IX_submissions_StudentId" ON submissions ("StudentId");

-- Stable IDs make the sample data easy to understand and reset.
INSERT INTO classes ("Id", "Name", "Section", "AcademicYear") VALUES
('10000000-0000-0000-0000-000000000001', 'Class 10', 'A', '2026')
ON CONFLICT DO NOTHING;

INSERT INTO subjects ("Id", "Name", "Code") VALUES
('20000000-0000-0000-0000-000000000001', 'Mathematics', 'MATH-10'),
('20000000-0000-0000-0000-000000000002', 'Physics', 'PHY-10'),
('20000000-0000-0000-0000-000000000003', 'English', 'ENG-10')
ON CONFLICT DO NOTHING;

INSERT INTO users ("Id", "FullName", "Email", "PasswordHash", "Role", "ClassId", "IsActive", "CreatedAt") VALUES
('30000000-0000-0000-0000-000000000001', 'System Administrator', 'admin@school.test', '100000.ABEiM0RVZneImaq7zN3u/w==.eDh9NKddpwgeM6+ZLeY3+1vk2zlCod7Gi7bOTnsEG7U=', 'Admin', NULL, true, NOW()),
('30000000-0000-0000-0000-000000000002', 'Nadia Rahman', 'teacher@school.test', '100000.ECEyQ1RldoeYqbrL3O3+Dw==.dJE6JYYejAGbgTY/f6NbRSe8n+98w3Ks9SlobI+UtjQ=', 'Teacher', NULL, true, NOW()),
('30000000-0000-0000-0000-000000000003', 'Ayan Ahmed', 'student@school.test', '100000./+7dzLuqmYh3ZlVEMyIRAA==.854x0dTitqbYAIFBEMKSBfWJbVH1IgMT7E0Utw3ul9A=', 'Student', '10000000-0000-0000-0000-000000000001', true, NOW()),
('30000000-0000-0000-0000-000000000004', 'Maliha Islam', 'student2@school.test', '100000./+7dzLuqmYh3ZlVEMyIRAA==.854x0dTitqbYAIFBEMKSBfWJbVH1IgMT7E0Utw3ul9A=', 'Student', '10000000-0000-0000-0000-000000000001', true, NOW())
ON CONFLICT DO NOTHING;

INSERT INTO teaching_assignments ("Id", "TeacherId", "ClassId", "SubjectId", "CreatedAt") VALUES
('40000000-0000-0000-0000-000000000001', '30000000-0000-0000-0000-000000000002', '10000000-0000-0000-0000-000000000001', '20000000-0000-0000-0000-000000000001', NOW())
ON CONFLICT DO NOTHING;

INSERT INTO assignments ("Id", "TeacherId", "ClassId", "SubjectId", "Title", "Description", "Deadline", "MaxMarks", "Status", "AllowResubmission", "CreatedAt", "UpdatedAt") VALUES
('50000000-0000-0000-0000-000000000001', '30000000-0000-0000-0000-000000000002', '10000000-0000-0000-0000-000000000001', '20000000-0000-0000-0000-000000000001', 'Quadratic Equations Practice', 'Solve the five quadratic equation problems and explain the method used for each answer.', NOW() + INTERVAL '7 days', 20, 'Published', true, NOW(), NOW()),
('50000000-0000-0000-0000-000000000002', '30000000-0000-0000-0000-000000000002', '10000000-0000-0000-0000-000000000001', '20000000-0000-0000-0000-000000000001', 'Geometry Revision', 'A draft assignment prepared for the next lesson.', NOW() + INTERVAL '14 days', 15, 'Draft', true, NOW(), NOW())
ON CONFLICT DO NOTHING;

INSERT INTO submissions ("Id", "AssignmentId", "StudentId", "AnswerText", "Status", "Marks", "Feedback", "SubmittedAt", "UpdatedAt", "ReviewedAt") VALUES
('60000000-0000-0000-0000-000000000001', '50000000-0000-0000-0000-000000000001', '30000000-0000-0000-0000-000000000004', 'I solved the equations by factorization and checked the roots by substitution.', 'Submitted', NULL, NULL, NOW(), NOW(), NULL)
ON CONFLICT DO NOTHING;

INSERT INTO settings ("Key", "Value", "Description", "UpdatedAt") VALUES
('SchoolName', 'Demo School and College', 'Name shown in the application header.', NOW()),
('DefaultAllowResubmission', 'true', 'Default resubmission preference for new assignments.', NOW())
ON CONFLICT ("Key") DO NOTHING;

COMMIT;
